version: '3.9'
services:
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - '8000:3000'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
    command: 'npm run dev'
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password